export const servicesOption = [
  "NRT/HND Airport Arrival Transfer",
  " Arrival Flight Details: TBA",
  "After disembarking, please follow the signs to the Immigration",
  "After clearing immigration, collect your baggage & meet our representative",
  "Transfer to City hotel - Tokyo/ Complete check in formalities",
  "Dinner at local Indian restaurant",
  "Transfer to Hotel",
  "Overnight stay at hotel in Tokyo",
  "Tokyo City Tour ~Asakusa (Sensoji), Nakamise, Tokyo Skytree, teamlab Borderless, Ginza shopping",
  "Pick up from Hotel @0900 Hrs",
  "Asakusa Kannon Temple (Sensoji ) - Tokyo's oldest and iconic temple",
  " Nakamise Dori ",
  "Tokyo Skytree - Climb up to the Tembo deck 350 m above ground and enjoy the spiralling skywalk 450 m high at the Tembo Galleria",
  "Stop for Lunch [Sumo wrestling and interaction - Yokozuna Tonkatsu Restaurant]",
  "Visit, teamLab Borderless: MORI Building DIGITAL ART MUSEUM",
  " Ginza Six Shopping Market ",
  " Dinner at local Indian restaurant",
  "Return to Hotel and free time for own activities",
  " Overnight stay at Hotel in Tokyo",
  "Mt Fuji and Hakone Tour by coach ~ Osahino Hakkai, Ōwakudani, Hakone Ropeway, Hakone Ship",
  "01 bag per person not exceeding 23 kgs. will be couriered to Kyoto hotel. Prepare a bag for overnight stay and keep all necessary medicines, prescription etc. in it",
  "Pick up from hotel and Visit Oshino Hakkai Village @0900 Hrs",
  "Oshino Hakkai (Springs of Mt. Fuji), a must-visit tourist spot (*weather permitting)",
  "Ōwakudani - an active volcanic valley (**weather permitting)",
  "Jigokudani - Famous for its black eggs, which are boiled in the sulphurous waters to give the egg shells a distinctive colour",
  "Stop for Lunch at Japanese restaurant",
  "Hakone Ropeway cable car and go sightseeing around the Ōwakudani Valley (weather permitting)",
  "Hakone Pirate Ship - go cruising from Togendai Port to Moto Hakone Port along Ashinoko Lake (**weather permitting)",
  "Return to Tokyo",
  " Dinner at local Indian restaurant",
  "Overnight stay at Hotel in Tokyo",
  "Tokyo to Kyoto Shinkansen Train/ Kyoto Tour ~Kyoto Station, Kyoto Railway Museum, Nijō Castle",
  " Check out and proceed to Tokyo station",
  "Tokyo station to Kyoto station in Bullet Train - Shinkansen Nozomi/ Hikari/ Sakura",
  "The travel between Tokyo to Kyoto takes about 2 hours and covers 513 kms",
  "Reach Kyoto and Visit Garden of Fine Arts Kyoto",
  "Shimogamo Hangi-cho, Sakyo-ku, Kyoto",
  "Stop for Lunch at Indian restaurant",
  "Experience Kimono wearing & Japanese Tea Ceremony ",
  "Enjoy Gion Corner: Traditional Arts Performance ",
  " Dinner at local Indian restaurant",
  "Reach hotel, Collect your bags and complete check in formalities",
  "Check in and free time for relaxation",
  " Overnight stay at hotel in Kyoto",
  "Kyoto Day Tour ~ Arashiyama, Kinkakuji, Imperial Palace, Tea Ceremony, Fushimi Inari Shrine",
  "Pick up from Hotel @0900 Hrs",
  "Miho Museum, Unique art museum in the mountains",
  "Walk through the Bamboo grooves",
  " Kinkaku-ji - Rokuon-ji is a Zen Buddhist temple, the “the Golden Pavilion”, Mirror Pond",
  " Kyoto Imperial Palace - the former palace of the Emperor of Japan (Drive pass/ No stop**)",
  "Stop for Lunch at Indian restaurant",
  "Kiyomizu-dera, known as the 'Temple of the Pure Water Spring'",
  "Dinner at local Indian restaurant",
  "Overnight stay at Hotel in Kyoto",
  "Nara Day Tour ~Tōdaiji Temple, Nara Deer Park, Kasuga Taisha shrine",
  "After breakfast, check out and meet our representative",
  "Proceed to Nara Tour (takes approx. 80 minutes to cover about 35 kms)",
  " Visit Tōdai-ji Temple - the world's largest wooden structure; home to the Great Buddha, the largest bronze statue in the world",
  " Nara Deer Park - renowned for its free-roaming deer and world famous temples",
  "Stop for Lunch at Indian restaurant",
  " Osaka Castle -  the most famous landmarks in Japan",
  " Umeda Sky Building - Floating Garden Observatory",
  "Dotonbori District (Shinsaibashi-Suji Shopping Street) - hotspot for tourists. Filled with towering neon signs, clubs, bars & restaurants",
  "Click a picture with the iconic Glico Man, shot from under Ebisubashi bridge, a famous Osaka picture spot",
  " Dinner  (**own arrangement)",
  "Reach Osaka hotel, complete check in formalities",
  "Overnight stay at Hotel in Osaka",
  "1-Day Hiroshima and Miyajima Tour (Round-trip from Osaka) ~Miyajima, Peace memorial, Bomb Dome",
  "Pick up from Hotel and transfer to Shin Osaka Station",
  "Shin Osaka station to Hiroshima station in Bullet Train - Shinkansen",
  "This super fast bullet train Journey takes less than 2 hours each way",
  "Upon reaching Hiroshima, Stop for lunch at local Indian restaurant",
  " After lunch, ferry transfer to Itsukushima Shrine",
  "Itsukushima Shrine - best known for its 'floating' torii gate",
  "See wild deer in Miyajima",
  "Return to Hiroshima main Island, ferry transfer",
  "Proceed to Hiroshima Peace Memorial Museum",
  "Atomic Bomb Dome (Hiroshima Memorial Park)",
  "Proceed to Hiroshima Station",
  "Hiroshima station to Shin Osaka station Bullet train ",
  "This super fast bullet train Journey takes less than 2 hours each way",
  "Pick up from Shin Osaka Station and transfer to restaurant",
  "Dinner at local Indian restaurant",
  "Free time for own activities. Overnight stay at hotel in Osaka",
  "Free time till check out or flight time",
  " Osaka city hotel to KIX/ITM Airport private transfer",
  "Departure Flight Details: TBA",
];

export const Inclusions = [
  "Hotel Accommodation with Breakfast as mentioned or similar",
  "All Tour and Transfers on private basis",
  "All Entrances/ Fees as mentioned",
  "Train Tickets in Economy Coach/ Reserved seats",
  "NRT/HND Airport Arrival Transfer",
  "Tokyo City Tour ~Asakusa (Sensoji), Nakamise, Tokyo Skytree, teamlab Borderless, Ginza shopping",
  "Mt Fuji and Hakone Tour by coach ~ Osahino Hakkai, Ōwakudani, Hakone Ropeway, Hakone Ship",
  "01 bag per person, not exceeding 23 kgs, courier from Tokyo hotel to Kyoto hotel",
  "Tokyo to Kyoto Shinkansen Train/ Kyoto Tour ~Kyoto Station, Kyoto Railway Museum, Nijō Castle",
  "Tokyo station to Kyoto station in Bullet Train - Shinkansen Nozomi/ Hikari/ Sakura",
  "Kyoto Day Tour ~ Arashiyama, Kinkakuji, Imperial Palace, Tea Ceremony, Fushimi Inari Shrine",
  "Nara Day Tour ~Tōdaiji Temple, Nara Deer Park, Kasuga Taisha shrine",
  "1-Day Hiroshima and Miyajima Tour (Round-trip from Osaka) ~Miyajima, Peace memorial, Bomb Dome",
  "Osaka city hotel to KIX/ITM Airport private transfer",
  "01 Lunch with Sumo wrestling and interaction - Yokozuna Tonkatsu Restaurant",
  "01 Lunch at Japanese Restaurant",
  "04 lunches & 07 Dinners at local Indian Restaurant (Buffet: 1 veg + 1 non veg Starter, 2 Veg + 2 Non Veg Main Course Curry, Roti, Rice, Achar, Chutney , 02 Desert (01 sweets + 01 Ice Cream))",
  "Services of English Speaking Guide for use as per itinerary; maximum 10 hours per day",
  "Services of JSD/ Vehicle for use as per itinerary; maximum 10 hours per day",
  "Use of 28/36/ 45 seater Isuzu Gala/ Hino Rainbow/ Similar Coach (*as per group size)",
  "01 litre water bottles per person per day in coach",
  "All tours must start at 0900 AM and end at 0700 PM / Must not exceed 10 Hours",
  "Driver & Vehicle for use as per itinerary for 10 hours maximum",
];
export const Exclusion = [
  "Any Airfare",
  "Any Visa charges",
  "Travel Insurance",
  "Any Tours & Transfers other than mentioned",
  "Any Porter charges",
  "Any meals other than mentioned",
  "Charges of personal nature like laundry, water etc.",
  "Surcharges as applicable due to peak season, surcharge dates, trade fair dates",
  "Any services not mentioned in the inclusions list",
];
export const TransportaionRules = [
  "10 hours of working each day",
  "Driver must have a 30-minutes break after every 5 hours of driving",
  "The driver’s working hours start 1 hour prior to the scheduled pick up time as advised by the clients",
  "Working hours must not exceed the 11-hour working limit (engine start to engine off)",
  "Dinner transfers must fit in the time frame if required",
  "After every 10 hours of working the driver must get 8 hours break before can restart driving the following day",
  "No extension of timings allowed due to new coach rules in Japan",
];
export const tourConditionData = [
  { condition: "Single Supplement", detail: "USD 100 Per Night" },
  { condition: "Triple Sharing", detail: "Full Tour Fare" },
  { condition: "Child with bed(Twin/Triple)", detail: "Full Tour Fare" },
  {
    condition: "Child without bed",
    detail:
      "50% of Tour Fare (Child below 12 year old), FOC (Child below 02 year old)",
  },
  { condition: "Meal condition", detail: "Breakfast at Hotel(included)" },
  {
    condition: "Tipping Guideline",
    detail:
      "Not mandatory in Japan; Souvenirs like home country coins, artifacts are liked as a token of appreciation",
  },
  {
    condition: "Bottle of water(500ML)",
    detail: "02 bottle per day per pax(included)",
  },
  {
    condition:
      "Given cost is for reference only. No bookings have been made and rates are subject to availability",
  },
  {
    condition:
      "Quotation is based on the Number of Passengers travelling together",
  },
  { condition: "Costs are nett and non-commissionable" },
  {
    condition:
      "Costs are subject to change due to currency fluctuations or any other statutory increases beyond our control",
  },
  {
    condition:
      "No Hotels or Tour service bookings have been made at the time of quotation",
  },
  {
    condition:
      "Hotels quoted are subject to availability. If not available, Hotels of Similar Grade will be booked",
  },
  {
    condition:
      "The itinerary can be altered due to unforeseen circumstances such as bad weather/ heavy traffic conditions. No refunds will be provided in such cases",
  },
  {
    condition:
      "Each Extra hour will be charges @ USD 80 for guide and USD 120 for Vehicle respectively; not exceeding 01 hour of over Time (11 hrs maximum per day)",
  },
  { condition: "Double Room is only on request basis, not guaranteed" },
  {
    condition:
      "Indian lunches & dinners and local meals are Pre-set and can’t be changed once confirmed",
  },
  {
    condition:
      "Indian Lunch/Dinner Menu -- (02 Veg Curry + 01 Non Veg Curry + 01 Dal + Assorted Roti / Naan + Rice/ Papad + Pickle)",
  },
  {
    condition:
      "Indian Dinner - (02 Veg Curry + 01 Non Veg Curry + 01 Dal + Assorted Roti / Naan + Rice / Papad + Pickle + 1 Dessert )",
  },
  { condition: "Quotation is valid for 04 days after submitting proposal" },
  {
    condition:
      "Bank charges to be borne by the remitter; All payment to be cleared before arrival of guest/ tour start",
  },
  { condition: "Note: Hotel rooms are relatively small in Japan" },
  {
    condition:
      "Coach and guide service shall be available only for 10 hours per day",
  },
  {
    condition:
      "Coach and guide services shall conclude by 1900 hrs due to Japanese Law",
  },
  {
    condition:
      "Please note that guests are required to walking an average of 4 to 6 kms per day; guest are requested to be physically and mentally ready",
  },
  {
    condition:
      "We strongly discourage the use of soft drink. Many places in Japan, require removing shoes before entering",
  },
  {
    condition:
      "Water bottle cost is included in proposal. Kindly keep the vehicle clean!",
  },
];
export const queryDashboardDummyData = [
  {
    adult: "2",
    child: "2",
    infant: "2",
    company: "VR Infra",
    name: "Ramesh Kumar",
    city: "Pune",
    address: "House no 16/A, Armay Colony",
    mobile: "1234567897",
    email: "asdfghjkl@gmail.com",
    status: "Open",
    duration: "10",
    queryDate: "2024-07-10",
    tourStartDate: "2024-07-19",
    uid: "02_PP19Jul24",
    agentHandling: "Raj Kumar ",
  },
  {
    adult: "1",
    child: "1",
    infant: "1",
    company: "QR Infra",
    name: "Subham Kumar",
    city: "Delhi",
    address: "House no 216/A, D Y Patil Colony",
    mobile: "2345678912",
    email: "qwertyuiop@gmail.com",
    status: "Open",
    duration: "10",
    queryDate: "2024-07-10",
    tourStartDate: "2024-07-19",
    uid: "02_PP19Jul25",
    agentHandling: "Arjun kumar ",
  },
];

export const dummyData = [
  {
    id: "1",
    groupName: "Holidaz",
    fileCode: "F12023",
    totalPax: "Fit",
    clientName: "Ms. Preeti",
    tourDate: "15 OCT 24–22 OCT 24",
    flight: "TBA",
    itinerary: "Tokyo 3 Nights + Kyoto 2 Nights + Osaka 2 Nights",
    dateOfQtn: "02-Jul-24",
    agent: "VIVEK TIWARI DEL",
    validity: "21-12-2023",
    services: [
      {
        city: "Pune",
        day: "D1",
        date: "25/12/2024",
        service: "NRT/HND Airport Arrival Transfer",
        duration: "4",
        mode: "mode",
        meal: "Veg",
      },
      {
        city: "Pune",
        day: "D1",
        date: "25/12/2024",
        service: "NRT/HND Airport Arrival Transfer",
        duration: "4",
        mode: "mode",
        meal: "Veg",
      },
      {
        city: "Pune",
        day: "D1",
        date: "25/12/2024",
        service: "NRT/HND Airport Arrival Transfer",
        duration: "4",
        mode: "mode",
        meal: "Veg",
      },
    ],
    hotels: [
      { city: "Pune", dates: "25/12/2023", nights: "1", hotel: "H1 Holiday" },
      { city: "Pune", dates: "26/12/2023", nights: "1", hotel: "H1 Holiday" },
      { city: "Pune", dates: "27/12/2023", nights: "1", hotel: "H1 Holiday" },
    ],
    quotationSlab: [
      {
        slab: "S1",
        minPax: "10",
        maxPax: "10",
        noOfFOC: "1",
        ppCost: "100000",
      },
      {
        slab: "S2",
        minPax: "15",
        maxPax: "10",
        noOfFOC: "1",
        ppCost: "130000",
      },
      {
        slab: "S3",
        minPax: "20",
        maxPax: "10",
        noOfFOC: "1",
        ppCost: "150000",
      },
    ],
  },
  {
    id: "2",
    groupName: "Adventure Seekers",
    fileCode: "F22023",
    totalPax: "Group",
    clientName: "Mr. John Doe",
    tourDate: "05 NOV 24–15 NOV 24",
    flight: "TBA",
    itinerary: "Paris 2 Nights + Rome 3 Nights + Berlin 3 Nights",
    dateOfQtn: "10-Jul-24",
    agent: "ANITA SHARMA MUM",
    validity: "21-12-2023",
    services: [
      {
        city: "Paris",
        day: "D1",
        date: "05/11/2024",
        service: "CDG Airport Arrival Transfer",
        duration: "2",
        mode: "Bus",
        meal: "Non-Veg",
      },
      {
        city: "Paris",
        day: "D1",
        date: "05/11/2024",
        service: "CDG Airport Arrival Transfer",
        duration: "2",
        mode: "Bus",
        meal: "Non-Veg",
      },
    ],
    hotels: [
      {
        city: "Paris",
        dates: "05/11/2024",
        nights: "2",
        hotel: "Hotel Parisian",
      },
      {
        city: "Paris",
        dates: "05/11/2024",
        nights: "2",
        hotel: "Hotel Parisian",
      },
    ],
    quotationSlab: [
      {
        slab: "S1",
        minPax: "15",
        maxPax: "20",
        noOfFOC: "2",
        ppCost: "150000",
      },
      {
        slab: "S1",
        minPax: "15",
        maxPax: "20",
        noOfFOC: "2",
        ppCost: "150000",
      },
    ],
  },
  {
    id: "3",
    groupName: "Nature Enthusiasts",
    fileCode: "F32023",
    totalPax: "Family",
    clientName: "Mrs. Jane Smith",
    tourDate: "20 DEC 24–30 DEC 24",
    flight: "TBA",
    itinerary: "Sydney 4 Nights + Melbourne 3 Nights",
    dateOfQtn: "15-Aug-24",
    agent: "RAHUL KUMAR BLR",
    validity: "21-12-2023",
    services: [
      {
        city: "Sydney",
        day: "D1",
        date: "20/12/2024",
        service: "SYD Airport Arrival Transfer",
        duration: "3",
        mode: "Car",
        meal: "Veg",
      },
      {
        city: "Sydney",
        day: "D1",
        date: "20/12/2024",
        service: "SYD Airport Arrival Transfer",
        duration: "3",
        mode: "Car",
        meal: "Veg",
      },
      {
        city: "Sydney",
        day: "D1",
        date: "20/12/2024",
        service: "SYD Airport Arrival Transfer",
        duration: "3",
        mode: "Car",
        meal: "Veg",
      },
    ],
    hotels: [
      { city: "Sydney", dates: "20/12/2024", nights: "4", hotel: "Sydney Inn" },
      { city: "Sydney", dates: "20/12/2024", nights: "4", hotel: "Sydney Inn" },
      { city: "Sydney", dates: "20/12/2024", nights: "4", hotel: "Sydney Inn" },
    ],
    quotationSlab: [
      { slab: "S1", minPax: "5", maxPax: "10", noOfFOC: "1", ppCost: "200000" },
      { slab: "S1", minPax: "5", maxPax: "10", noOfFOC: "1", ppCost: "200000" },
      { slab: "S1", minPax: "5", maxPax: "10", noOfFOC: "1", ppCost: "200000" },
    ],
  },
];
